const fs = require('node:fs')
const path = require('node:path')
const Ajv = require('ajv')
const standalone = require('ajv/dist/standalone').default
const schema = require('../src/native/schema')
const root = path.resolve(__dirname, '../src/native')
const ajv = new Ajv({strict: true, allErrors: true, code: {source: true, lines: true}, useDefaults: false, coerceTypes: false, removeAdditional: false})
fs.writeFileSync(path.join(root, 'ergogen-v1.schema.json'), JSON.stringify(schema, null, 2) + '\n')
fs.writeFileSync(path.join(root, 'validate.js'), '// Generated by scripts/build-schema.js. Do not edit.\n' + standalone(ajv, ajv.compile(schema)))
