use boardstudio_core::model::*;
use std::{env, fs, path::PathBuf};
use ts_rs::{Config, TS};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output = env::var_os("CONTRACTS_OUT_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("../contracts/src/generated"));
    fs::create_dir_all(&output)?;

    let config = Config::new().with_large_int("number").with_out_dir(output);
    macro_rules! export {
        ($($type:ty),+ $(,)?) => { $(<$type>::export(&config)?;)+ };
    }
    export!(
        Vec2,
        Vec3,
        Pose2,
        Material,
        Pad,
        PadShape,
        PartModel,
        KicadSource,
        PartDefinition,
        EnvelopeSource,
        EnvelopeOrigin,
        MatrixTerminals,
        PartGenerator,
        PartKind,
        Part,
        Side,
        Pin,
        Net,
        Matrix,
        Layout,
        LayoutMirrorLink,
        MatrixCell,
        MatrixAssembly,
        Mirror,
        DiodeDirection,
        PartOutline,
        CornerStyle,
        OutlineSettings,
        OutlineFeature,
        Operation,
        Board,
        CopperTrace,
        CopperVia,
        CaseBody,
        Mount,
        MountKind,
        Gasket,
        CaseKind,
        Asset,
        Script,
        Constraint,
        MirrorAxis,
        ProjectDoc,
        EditOperation,
        Position,
        EditPhase,
        EditCommand,
        Contour,
        CaseIR,
        CaseAssemblyIR,
        PreparedCaseIR,
        PreparedCaseRegion,
        PreparedGasketRegion,
        PreparedCaseAssemblyIR,
        Severity,
        Scope,
        Finding,
        Readiness,
        Transform,
        BoardContours,
        BoardReadiness,
        SceneDelta,
        CoreRequest,
        CoreReply,
        OutlineExportFormat,
        LocalTrace,
        LocalVia,
        FootprintGeometry,
        ArtifactDiagnosticKind,
        ArtifactDiagnostic,
        CompiledFootprint,
        FootprintCompileJob,
        ArtifactErrorCode,
        ArtifactError,
        FootprintPatch,
        PrepareExportRequest,
        ExportTarget,
        ErgogenJob,
        ReservedNet,
        ExportPlan,
        ErgogenJobResult,
        FinishExportRequest,
        ArtifactFile,
        ExportArtifact,
        OutlineExportRequest,
        ArtifactRequest,
        ArtifactReply,
    );
    Ok(())
}
