import { expect, it } from 'vitest';
import type { ElectricalPlan } from '@boardstudio/v2-contracts';
import { peripheralFirmware } from './firmwarePeripherals';

const base = (kind: string): ElectricalPlan => ({ instanceId:null, jumpers:[], moduleAliases:{}, peripheralTerminals:{}, mode: 'matrix', assignments: [], rowPins: [], columnPins: [], diagnostics: [], fingerprint: 'x', boardId: 'b', controllerPartId: 'm', revision: 1, controllerProfile: 'ceoloide/mcu_nice_nano', freePins: [], nets: [], diodeDirection: 'col2row', peripherals: [{ partId: 'disp', source: 'test', kind, gpioTerminals: [], fixedTerminals: [] }], peripheralPins: { 'disp/i2c/SDA': 'P0.20', 'disp/i2c/SCL': 'P0.22', 'disp/spi/MOSI': 'P0.20', 'disp/spi/SCK': 'P0.22', 'disp/CS': 'P0.24' } });
it('emits source-compatible SSD1306 overlay with allocated GPIOs', () => { const out = peripheralFirmware(base('display-i2c')); expect(out.overlays[0]).toContain('solomon,ssd1306fb'); expect(out.overlays[0]).toContain('NRF_PSEL(TWIM_SDA, 0, 20)'); expect(out.overlays[0]).toContain('prechargep = <0x22>'); expect(out.config).toContain('CONFIG_SSD1306=y'); expect(out.overlays[0]).toContain('zephyr,display = &oled'); });
it('emits sharp nice_view overlay with allocated GPIOs', () => { const out = peripheralFirmware(base('display-spi')); expect(out.overlays[0]).toContain('sharp,ls0xx'); expect(out.overlays[0]).toContain('NRF_PSEL(SPIM_MOSI, 0, 20)'); expect(out.overlays[0]).toContain('spi-max-frequency = <1000000>'); expect(out.config).toContain('CONFIG_LS0XX=y'); });
it('emits decimal GPIO cells and honors terminal role mappings', () => { const plan = base('display-spi'); plan.peripheralPins = { 'disp/spi/MOSI': 'P0.08', 'disp/spi/SCK': 'P1.09', 'disp/CS': 'P0.04' }; plan.peripherals[0].gpioTerminals = [['MOSI', 'spi/MOSI'], ['SCK', 'spi/SCK'], ['CS', 'CS']]; const out = peripheralFirmware(plan); expect(out.overlays[0]).toContain('NRF_PSEL(SPIM_MOSI, 0, 8)'); expect(out.overlays[0]).toContain('NRF_PSEL(SPIM_SCK, 1, 9)'); expect(out.overlays[0]).toContain('&gpio0 4 GPIO_ACTIVE_HIGH'); });
it('emits source-compatible EC11 encoder and RGB overlays', () => { const plan = base('encoder'); plan.peripheralPins = { 'disp/encoder/A': 'P0.08', 'disp/encoder/C': 'P0.09' }; plan.peripherals[0].gpioTerminals = [['A', 'encoder/A'], ['C', 'encoder/C']]; const out = peripheralFirmware(plan); expect(out.overlays[0]).toContain('compatible = "alps,ec11"'); expect(out.overlays[0]).toContain('steps = <80>'); const rgb = base('rgb'); rgb.peripheralPins = { 'disp/rgb-in': 'P0.04' }; rgb.peripherals[0].gpioTerminals = [['DIN', 'rgb-in']]; expect(peripheralFirmware(rgb).overlays[0]).toContain('worldsemi,ws2812-spi'); });
it('resolves unscoped bus pins from the electrical plan', () => { const plan = base('display-i2c'); plan.peripheralPins = { 'i2c/SDA': 'P0.20', 'i2c/SCL': 'P0.22' }; expect(peripheralFirmware(plan).overlays[0]).toContain('NRF_PSEL(TWIM_SCL, 0, 22)'); });
it('reports mixed display buses as a hardware resource conflict', () => { const plan = base('display-i2c'); plan.peripherals.push({ ...plan.peripherals[0], partId: 'view', kind: 'display-spi' }); expect(() => peripheralFirmware(plan)).toThrow(/separate hardware peripherals/); });
