const fs=require('fs'),path=require('path'),cp=require('child_process'),crypto=require('crypto');
const d=__dirname,ts=require(process.cwd()+'/app/node_modules/typescript');
const repoManifest=require(d+'/repositories.json');const roots=repoManifest.map(r=>r.localDir);
const rows=[],repos=[],seen=new Set();
function props(n){return n&&ts.isObjectLiteralExpression(n)?n.properties.filter(p=>p.name).map(p=>[p.name.text||p.name.getText(),p.initializer]):[]}
for(const dir of roots){if(!fs.existsSync(dir+'/.git'))continue;const git=(...a)=>cp.execFileSync('git',['-C',dir,...a],{encoding:'utf8'}).trim();const origin=git('remote','get-url','origin').replace(/\.git$/,'').replace(/^git@github.com:/,'https://github.com/');const repo=origin.replace('https://github.com/','');if(seen.has(repo))continue;seen.add(repo);const sha=git('rev-parse','HEAD');if(repoManifest.find(r=>r.repo===repo)?.sha!==sha)throw new Error('Pinned SHA mismatch '+repo);const files=git('ls-tree','-r','--name-only','HEAD').split('\n');const licenses=files.filter(f=>/(^|\/)(licen[sc]e|copying)(\.|$)/i.test(f));let count=0;
for(const f of files.filter(f=>f.endsWith('.js')&&!f.includes('node_modules/'))){const src=fs.readFileSync(path.join(dir,f),'utf8');if(repo==='ergogen/ergogen'&&!f.startsWith('src/footprints/'))continue;if(!/\bbody\s*[:(]/.test(src)||!/(module\.exports|exports\.)/.test(src))continue; const ast=ts.createSourceFile(f,src,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS);let obj;
function visit(n){if(ts.isBinaryExpression(n)&&n.left.getText(ast)==='module.exports')obj=n.right;ts.forEachChild(n,visit)}visit(ast);const top=props(obj),pr=props(top.find(([k])=>k==='params')?.[1]);if(!top.some(([k])=>k==='body'))continue;
const schema=pr.map(([k,v])=>({name:k,value:v?.getText(ast)||'undefined'}));const netParams=schema.filter(p=>p.value==='undefined'||/type\s*:\s*['"]net['"]/.test(p.value)).map(p=>p.name);const flags=schema.filter(p=>['side','reverse','reversible','reverse_mount','hotswap','solder','include_traces','include_traces_vias','hotswap_pads_same_side'].includes(p.name));const legacyNets=top.find(([k])=>k==='nets');const legacyNetParams=props(legacyNets?.[1]).map(([k])=>k);rows.push({repo,sha,path:f,url:origin+'/blob/'+sha+'/'+encodeURI(f),sha256:crypto.createHash('sha256').update(src).digest('hex'),contract:legacyNets?'legacy nets+params':'params/body',netParams,legacyNetParams,controls:Object.fromEntries(flags.map(p=>[p.name,p.value])),params:schema,fileLicense:(src.match(/SPDX-License-Identifier:\s*([^\n\r]+)/)||[])[1]||null,repositoryLicenseFiles:licenses,verification:'source inventory only; not runtime-qualified',localDir:dir});count++;}
repos.push({repo,sha,url:origin+'/tree/'+sha,localDir:dir,commitDate:git('show','-s','--format=%cI','HEAD'),moduleCount:count,licenseFiles:licenses,rawKicadCount:files.filter(f=>f.endsWith('.kicad_mod')).length});}
fs.writeFileSync(d+'/catalogue.json',JSON.stringify(rows,null,2)+'\n');fs.writeFileSync(d+'/repositories.json',JSON.stringify(repos,null,2)+'\n');
const quote=v=>'"'+String(v??'').replaceAll('"','""')+'"'; const cols=['repo','sha','path','contract','netParams','legacyNetParams','controls','fileLicense','sha256','url','verification'];fs.writeFileSync(d+'/catalogue.csv',cols.join(',')+'\n'+rows.map(r=>cols.map(k=>quote(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])).join(',')).join('\n')+'\n');console.log(JSON.stringify({repositories:repos.length,files:rows.length,uniqueHashes:new Set(rows.map(x=>x.sha256)).size,byRepo:repos.map(r=>[r.repo,r.moduleCount])},null,2));
