const fs=require('fs'),path=require('path');const d=__dirname,now=new Date().toISOString(),rows=require(d+'/catalogue.json'),notes=require(d+'/local-notes.json');
const claims=[
['C01','39 family modules have complete pin-relative hash/patch accounting','supported','I1','local-provenance.json;verify-inventory.json','inventory worker;root pinned-file hash comparison','Integrity record, not correctness proof'],
['C02','Choc B single unplated same-side assigns both socket contacts FROM','supported','I2,I3','verify-switches.jsonl;verify-switches-upstream.jsonl','switch family;independent verifier;root native replay','Control variants retain both signals; solder pads may still carry TO'],
['C03','MX reversible default track metadata conflicts with contacted pads','supported','I2,I3','verify-switches.jsonl','switch family;independent verifier;root native replay','Geometric short not proven; source chains connect corresponding contacts'],
['C04','Infused MCU fixed numeric segment IDs become wrong board-local named tags','supported','I2,I4','verify-local.json;assets/infused-kim_nice_nano_pretty_named.kicad_pcb','controller source;integration native;root native;fresh controller reviewer','Not a claim of physical short'],
['C05','Ceoloide reversible MCU segments omit net fields','supported','I2,I4','verify-local.json;assets/ceoloide_mcu_nice_nano_named.kicad_pcb','controller source;root native;fresh controller reviewer','Desktop rebuild consequences unresolved'],
['C06','Accepted diode option combination emits zero pads','supported','I2,I3','verify-local.json;assets/padless_diode.kicad_pcb','peripheral;skeptic;root native','Option documented reversible; missing incompatible-option validation'],
['C07','Infused six-pad defaults alias PAD_5 on two pads per face','supported','I2','verify-local.json;assets/six_pads_defaults.kicad_pcb','peripheral;root;fresh execution reviewer','F5/6 B1/2; explicit net6 override can avoid default alias'],
['C08','MX stabilizer gate/width controls do not implement declared intent','supported','I3','verify-switches.jsonl;../../../../ts-boardstudio2/footprints/switch_mx.js','switch source;independent native probe','Widths source-only; net gates executed'],
['C09','SSD1306 custom ground width applies VCC-adjacent paths','supported','I2,I3','verify-edge.json;assets/ssd-width-false.kicad_pcb','controller;fresh controller native;root native','Reversible+traces+unequal widths only; no signal short claim'],
['C10','Keepout shorthand F&B becomes NaN default layer; F/B rejected','supported','I3,I4','verify-edge.json;assets/keepout-default.kicad_pcb','fresh variants;fresh execution;root native','Explicit F&B yields intended token; no other semantic collision found in local scan'],
['C11','Front/back, reversible, model orientation and layout mirroring differ','supported','I3','local-notes.json;AUDIT.md','family workers;fresh variants review','Provider-specific, not universal parameter semantics'],
['C12','Some reversible layouts require routing and selected bridges','supported','I2,I3','verify-local.json;local-notes.json','peripheral/controller sources;root native','Source omits tracks intentionally in some families'],
['C13','132 measured raw/staged result summaries match','supported','I4','compare-staging.cjs;staging-comparison.json;staged/verify-local.json','root independent raw/staged generation','Not all geometry or raw-byte equality'],
['C14','Complete existing footprint suite passed Node24 invocation','supported','I6','footprint-tests.txt;footprint-tests-receipt.json','root actual suite run','Passing models tests cannot prove net separation'],
['C15','Catalogue has346records306hashes27positive of34repos','supported','I5','catalogue.json;repositories.json;catalogue-counts.json','rootAST extraction;fresh catalogue exhaustive hash review','26thirdparty+official;7contextonly;no universal GitHub completeness'],
['C16','Legacy top-level nets differ from current executor contract','supported','I5','catalogue.json;catalogue-data.cjs;MASTER_CATALOGUE.md','official source;fresh contract12row probe;root schema extraction','12legacy records require migration; no external qualification'],
['C17','Source licenses require per-file/model scope; identified notices conflict','supported','I1,I5','license-audit.md;catalogue.json;repository-metadata.json','license worker;fresh license reviewer;root actualLICENSE/README check','Primary-only exception for what each source states; no legal-clearance conclusion'],
['C18','Six supplementary runtime registrations generate in default smoke cases','supported','I6','verify-supplement.json;verify-supplement.cjs','root native runtime','Single-source execution exception; no full variant/physical audit'],
['R01','Matching upstream pins implies electrically correct variants','refuted','I2','verify-switches-upstream.jsonl','upstream generator;independent verifier','Inheritance reproduces defects'],
['R02','Repeated pad numbers alone prove physical short','refuted','I2','https://docs.kicad.org/10.0/en/pcbnew/pcbnew.html#pad_connections_net_ties_and_jumper_pads','official manual;geometry/source reviewer','Same-net duplicates can be intentional'],
['R03','Keepout B rejection is a correct negative test','refuted','I3','verify-edge.json','source contract;independent runtime','Superseded by C10'],
['R04','Current wizard silently ignores unknown reverse/reversible params','refuted','I4','/home/chris/projects/ts-boardstudio2/engine/src/pcbs.js','engine source;contract review','Current executor rejects unknown params except special mirror'],
['R05','GitHub API null/NOASSERTION establishes absence of license','refuted','I5','license-audit.md;MASTER_CATALOGUE.md','sourceLICENSE/README;fresh claims review','MIT rawlibrary andUT22README corrected'],
['U01','Desktop KiCad normalization and DRC outcome for emitted tracks','unresolved','I2','assets/infused-kim_nice_nano_pretty_named.kicad_pcb;verify-switches.jsonl','root and reviewers','No installed kicad-cli; generated artifacts retained'],
['U02','LED physical-view/pad numbering equivalence across both mounting modes','unresolved','I2,I3','https://github.com/ceoloide/ergogen-footprints/issues/80','issue;manufacturer Rev02;fresh physical reviewer','Logical function table agrees with local header; view-level dispute not closed'],
['U03','Gateron overlapping drill acceptance/custom-pad arbitrary-angle safety','unresolved','I3','/home/chris/projects/ts-boardstudio2/footprints/switch_gateron_ks27_ks33.js','source geometry;switch reviewer','No fabrication or full native DRC'],
['U04','Schematic-update behavior for same-number/different-net providers','unresolved','I2','local-notes.json;verify-local.json','source;root pads inventory','No native schematic roundtrip'],
['U05','Unlicensed/conflicting third-party redistribution scope','unresolved','I5','license-audit.md','source statements;independent license review','Requires source-owner clarification/legal scope decision, catalogue remains link-only'],
['U06','Exact Alps target fit and all optional/physical variants','unresolved','I3','/home/chris/projects/ts-boardstudio2/footprints/BOARDSTUDIO.md','existing declared limits;fresh reviewers','No new model supplied/physical evidence; no fabrication assurance']];
let graph='# Claim graph\n\n## Verified claims digest\n\nC01–C18 supported within stated scopes. Numeric counts derive from exact source/runtime artifacts. Non-code license assertions only describe primary notices, with a primary-source-only exception; no legal interpretation is asserted. R01–R05 refuted. U01–U06 unresolved and excluded from positive assurance.\n';
for(const[cid,statement,status,intents,obs,groups,counter]of claims){graph+=`\n## ${cid}\n\n- Statement: ${statement}\n- Type: ${cid==='C17'?'source-notice non-code':'code/source/runtime or documented limitation'}\n- Risk: ${/^C0[2-9]$|C10/.test(cid)?'high':'normal'}\n- Scope: current inspected worktree; pinned sources; variants named in artifacts\n- Intent IDs: ${intents}\n- Supporting observations: ${obs}\n- Contradicting observations / counter-search: ${counter}\n- Independent observation groups: ${groups}\n- Convergence: ${status==='supported'?'source/runtime/review converged or explicit primary-only exception':status}\n- Primary backing: actual source or executed generator output in listed artifacts\n- Dependencies: ${cid==='C13'?'C02–C10 raw/staged observations':'none outside listed evidence'}\n- Status: ${status}\n- Synthesis location: AUDIT.md / MASTER_CATALOGUE.md\n`;}
graph+='\n## Catalogue declaration nodes\n\nEvery file row below is a source-declaration claim, not support/qualification. Risk normal; intentI5; supporting observation O-C<n> is that exact pinned source parsed by catalogue-data.cjs; countercheck is file SHA-256 and contract shape; no contradicting source observed. Independent groups: root static extraction and fresh catalogue exhaustive pin/hash review (same primary source). Primary-only exception: a file is authoritative for its own declared API. Convergence supported for declared API only; dependencies C15/C16; synthesis MASTER_CATALOGUE per-repo row.\n\n';rows.forEach((r,i)=>{graph+=`- C-M${i+1}: [${r.repo}/${r.path}](${r.url}) declares ${r.contract}; current nets [${r.netParams.join(',')}], legacy nets [${(r.legacyNetParams||[]).join(',')}]; status supported; O-C${i+1}.\n`;});
fs.writeFileSync(d+'/claim-graph.md',graph);
let obs='# Observation manifest\n\n| ID | Source | Layer | Observer group / independence | Observer | observed_at | valid_at | Artifact / anchor | Contamination |\n|---|---|---|---|---|---|---|---|---|\n';claims.forEach((c,i)=>obs+=`| O${i+1} | ${c[4].replaceAll('|','/')} | source/runtime | ${c[5]} | workers/root/reviewers | ${now} | inspected pins + current worktree; capture chronology in wave notes | ${c[0]} artifacts | shared source distinguished from independent method; no approval from popularity |\n`);rows.forEach((r,i)=>obs+=`| O-C${i+1} | ${r.url} | pinned code | static root + independent pin/hash audit | root / fr_catalogue | ${now} | ${r.sha} | catalogue.json ${r.path} sha256:${r.sha256} | same source; primary-only declaration exception |\n`);fs.writeFileSync(d+'/observation-manifest.md',obs);
fs.writeFileSync(d+'/intent-diff.md','# Intent versus reality\n\n| ID | Expected truth | Observed reality | Diff / invariant | Intent source | Observations | Status | Claims |\n|---|---|---|---|---|---|---|---|\n| I1 | Borrowed source traceable to pins/patches |39 hashes accounted; patch descriptions sometimes incomplete | Integrity true; narrative provenance needs precision | User borrowed footprints audit | provenance and actual diffs | true with documented caveat | C01,C17 |\n| I2 | Pads and tracks preserve intended independent signals | Choc collapse, MX/vendor MCU tags, pad6 alias, padless option | Signal membership / copper ownership violated | User correct pad mappings | native PCB outputs | violated | C02–C09,U01,U02,U04 |\n| I3 | Side/reversible variants implement declared intent | family-specific semantics; keepout invalid default; selected options misleading | Variant contracts violated in named cases | User front/back/reversible | verify-switches/edge/local | violated | C02,C03,C06,C08–C12,U03,U06 |\n| I4 | Staging preserves copper and native conversion correctly interprets it | raw/staged summaries equal; fixed IDs remain wrong; shorthand typing fails | Fidelity is not repair | User changes KiCad footprint | staging-comparison/native outputs | violated for interpretation; measured staging fidelity true | C04,C10,C13,R04 |\n| I5 | Master list has pinned source, contract and provenance |346records27positive/34inspectedrepos; legacy flags and license gaps explicit | Source inventory complete within inspected set; no runtime/fabrication claim | User popular GitHub master list | catalogue/repo metadata/license audit | true within declared scope | C15–C17,U05 |\n| I6 | Audit evidence distinguishes proof levels | repeated root execution, fresh reviews, DRC unavailable, supplementary6smoke only | limitations retained | Research workflow | receipts and QA | true | C14,C18,U01–U06 |\n');
fs.writeFileSync(d+'/cause-disappearance.md','# Cause status\n\nNo product fix was made. No confirmed defect is claimed to have disappeared.\n\n| Cause | Expected truth | Previous / last_seen | Disconfirming evidence | Replacement | Current state | Violation no longer observed? |\n|---|---|---|---|---|---|---|\n'+claims.filter(c=>/^C0[2-9]$|C10/.test(c[0])).map(c=>`| ${c[0]} | ${c[3]} contract | ${c[4]} @ ${now} | controls constrain scope; not disappearance | none | observed under named trigger | no |`).join('\n')+'\n| R03 | keepout B should work | initial report misclassified rejection | source F/B contract; native NaN.Cu | C10 engine inference | initial explanation withdrawn | no, actual defect remains |\n| R05 | source notice governs metadata | API-null fallback | pinned LICENSE/README | corrected master table | report defect corrected | yes, wording corrected only |\n');
fs.writeFileSync(d+'/verification-economics.md','# Verification decisions\n\n| Claim / batch | Risk / error cost | Verification cost | Chosen path | Decision and result | Residual risk |\n|---|---|---|---|---|---|\n|C01 provenance|medium, wrong borrowed source|39hash comparisons cheap|pinned clones+manifest+retained diffs|verify;39complete|semantic patch reason omissions|\n|C02/C03/C08 switches|high defective PCBs|45cases/source cheap|distinct nets+rotations native+upstream|verify; defects scoped|desktop DRC/physical assembly|\n|C04–C07 family scope|high wrong copper|132raw cases cheap|native generation+parsedpads/tracks|verify;131generate1reject, not131electrical passes|zones initially absent fromsummary, corrected edge batch|\n|C13 staging|medium incorrect blame|132staged cases cheap|raw/staged132case comparison|verify;selected inventories equal|models/full geometry not compared|\n|C09/C10 options|high invalidboard|10native calls cheap|keepout4,SSD2,MCUtoggles4|verify; retained PCB/JSON|desktop acceptance unknown|\n|C18 supplementary|medium scope ambiguity|6native cases cheap|default distinct-net smoke|verify;6generate|no fullvariant orphysical audit|\n|C14 existing suite|medium falseassurance|seconds|actualpnpm+Node24|pass;limited test scope|electrical separation not universally tested|\n|C15/C16 external inventory|medium incorrect catalogue|AST+allhashes modest|346pinnedfiles34repos|verify;legacy12 marked|notexternal runtimequalification|\n|C17 license notices|high incorrect permission|read primary records modest|perfile notices+actualLICENSE/README|verify statements only;unknowns retained|no legal clearance|\n|U01–U06 physical/DRC|high fabrication risk|requires absent binary/hardware|do not infer from source|defer explicit unresolved|fabricationnotqualified|\n');
