const fs=require('fs'),path=require('path'),vm=require('vm');const root=process.cwd(),d=process.env.PROBE_OUTPUT_DIR||__dirname,e=require(root+'/engine/src/ergogen'),sx=require(root+'/engine/src/templates/sexpr');
const manifest=require(root+'/footprints/manifest/sources.json'),staged=require(root+'/app/.generated/footprints.json');const ch=(n,k)=>n.find(x=>Array.isArray(x)&&x[0]===k),chs=(n,k)=>n.filter(x=>Array.isArray(x)&&x[0]===k);const val=sx.value;
const mods=[];for(const[ns,files]of Object.entries(manifest.footprints))for(const f of Object.keys(files)){const file=ns==='ceoloide'?f:'vendor/infused-kim/'+path.basename(f),name=(ns==='ceoloide'?'ceoloide':'infused-kim')+'/'+path.basename(file,'.js');let mod=require(root+'/footprints/'+file);if(process.env.STAGED){const ctx={module:{exports:{}}};vm.runInNewContext(staged[name],ctx);mod=ctx.module.exports;}mods.push({name,file,module:mod});}
function summarize(board){const b=sx.parse(board,'probe')[0];return{footprints:b.filter(x=>Array.isArray(x)&&['module','footprint'].includes(x[0])).map(fp=>({name:val(fp[1]),pads:chs(fp,'pad').map(p=>({number:val(p[1]),type:p[2],at:ch(p,'at')?.slice(1),layers:ch(p,'layers')?.slice(1).map(val),net:ch(p,'net')?val(ch(p,'net').at(-1)):null}))})),segments:chs(b,'segment').map(s=>({net:ch(s,'net')?val(ch(s,'net').at(-1)):null,start:ch(s,'start')?.slice(1),end:ch(s,'end')?.slice(1),width:ch(s,'width')?.[1],layer:val(ch(s,'layer')?.[1]||'')})),vias:chs(b,'via').length};}
async function run(m,label,overrides={},save=false){const params={};for(const[k,v]of Object.entries(m.module.params||{})){if(v===undefined||v&&typeof v==='object'&&v.type==='net')params[k]='SIG_'+k;}Object.assign(params,overrides);if(label==='six_pads_defaults')for(const k of Object.keys(params))if(k.startsWith('net_'))delete params[k];e.inject('footprint',m.name,m.module);const cfg={schema:'ergogen/v1',layout:{objects:{component:{kind:'component',pcb:'main',footprints:{main:{what:m.name,params}}}}},designs:{regions:{board:{shape:{size:[200,200]}}},profiles:{board:{from:'regions.board'}}},pcbs:{main:{profile:'profiles.board'}}};try{const r=await e.process(cfg,{analysis:true});const inventory=summarize(r.pcbs.main);if(save)fs.writeFileSync(d+'/assets/'+label+'.kicad_pcb',r.pcbs.main);return{name:m.name,label,params,ok:true,inventory,findings:r.layout?.findings||[]};}catch(err){return{name:m.name,label,params,ok:false,error:err.message};}}
(async()=>{const results=[];for(const m of mods){const variants=[['default',{}]];if('side'in m.module.params)variants.push(['back',{side:'B'}]);for(const p of ['reverse','reversible'])if(p in m.module.params){variants.push([p,{[p]:true}]);if('side'in m.module.params)variants.push([p+'_back',{[p]:true,side:'B'}]);}for(const[label,p]of variants)results.push(await run(m,m.name.replace('/','_')+'_'+label,p));}
const get=n=>mods.find(m=>m.name===n);results.push(await run(get('ceoloide/diode_tht_sod123'),'padless_diode',{include_thru_hole_smd_pads:true},true));results.push(await run(get('infused-kim/pads'),'six_pads_defaults',{pads:6,net_1:'PAD_1',net_2:'PAD_2',net_3:'PAD_3',net_4:'PAD_4',net_5:'PAD_5',net_6:'PAD_5'},true));
for(const n of ['ceoloide/mcu_nice_nano','infused-kim/nice_nano_pretty'])results.push(await run(get(n),n.replace('/','_')+'_named',n.startsWith('ceoloide')?{reversible:true,P0:'C1',P1:'R1'}:{P0:'C1',P1:'R1'},true));
fs.writeFileSync(d+'/verify-local.json',JSON.stringify({node:process.version,engine:e.version,results},null,2));const failures=results.filter(r=>!r.ok).map(({name,label,error})=>({name,label,error}));console.log(JSON.stringify({cases:results.length,success:results.length-failures.length,failures},null,2));
})().catch(err=>{console.error(err);process.exitCode=1});
